apiVersion: apps/v1
kind: Deployment
metadata: { name: prometheus, namespace: whatsapp }
spec:
  replicas: 1
  selector: { matchLabels: { app: prometheus } }
  template:
    metadata: { labels: { app: prometheus } }
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.53.0
          args: [ "--config.file=/etc/prometheus/prometheus.yml" ]
          ports: [ { containerPort: 9090 } ]
          volumeMounts:
            - name: cfg
              mountPath: /etc/prometheus
      volumes:
        - name: cfg
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata: { name: prometheus-server, namespace: whatsapp }
spec:
  ports: [ { port: 9090, targetPort: 9090 } ]
  selector: { app: prometheus }
---
apiVersion: v1
kind: ConfigMap
metadata: { name: prometheus-config, namespace: whatsapp }
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            separator: ;
            regex: (\d+);(.*)
            replacement: $2:$1
